# Generated by Django 5.2.1 on 2025-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(default=54, max_length=243),
            preserve_default=False,
        ),
    ]
