# Generated by Django 5.2.1 on 2025-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0003_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
