# Generated by Django 5.2.4 on 2025-07-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic/')),
                ('name', models.CharField(max_length=22)),
                ('desc', models.TextField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('destination', models.CharField(max_length=18)),
                ('is_top', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=13)),
                ('cus_phn', models.BigIntegerField()),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.package')),
            ],
        ),
    ]
