# Generated by Django 5.2.4 on 2025-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
