# Generated by Django 5.2.1 on 2025-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
