# Generated by Django 5.2.1 on 2025-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0002_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=78),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
