# Generated by Django 5.2.1 on 2025-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0003_remove_student_last_name_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=10000)),
                ('desc', models.CharField(max_length=500000)),
            ],
        ),
    ]
