# Generated by Django 5.2.1 on 2025-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(max_length=1234556),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
