# Generated by Django 5.2.1 on 2025-06-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0006_destination_price_alter_booking_cus_ph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
    ]
