# Generated by Django 5.2.1 on 2025-06-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0007_remove_destination_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_ph',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='frm.student'),
            preserve_default=False,
        ),
    ]
