# Generated by Django 5.2.1 on 2025-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0008_rename_name_booking_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='student',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
