# Generated by Django 5.2.1 on 2025-06-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0009_remove_booking_student_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='cus_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_phone',
            new_name='cus_phone',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='destination',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
