# Generated by Django 5.2.1 on 2025-06-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0010_rename_customer_name_booking_cus_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='destination',
        ),
    ]
