# Generated by Django 5.2.1 on 2025-06-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0011_rename_name_booking_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cus_phone',
            field=models.IntegerField(),
        ),
    ]
