# Generated by Django 5.2.1 on 2025-06-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0012_alter_booking_cus_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cus_phone',
        ),
    ]
