# Generated by Django 5.2.1 on 2025-06-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frm', '0013_remove_booking_cus_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
